### PR TITLE
the end date is set to 1st of next month as the upperbound is excluded

### PR DESCRIPTION
**Pull request by acn-dgopa**
## Description

- the end date is set to 1st of next month as the upperbound is excluded
- also a new tabl version is created to avoid overlapping confusion with the existing partitions with different dateranges

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by Alxandr** [comment]
Wait, why are we making v2 of the table?

**Comment by acn-dgopa** [comment]
> Wait, why are we making v2 of the table?

The existing partition december has date range until 05 january in production, 11 in AT environments. We cannot change the partition range without removing them which means data will be lost. So data has to be any way migrated. So my plan here is to create new table and partitions with monthly date range and migrate the data from v1 to v2. Probably this is not very optimal solution. Any thoughts?

**Comment by Alxandr** [comment]
https://www.enterprisedb.com/blog/altering-bounds-partition - rather than using a migration to create v2, use one to alter the bounds (if the table exists).

**Comment by acn-dgopa** [comment]
The script is run manuallly in all the evironments to alter the parition ranges.

**Pull request merged**
